# 1. which channel is most frequently used for transactions?

select count(store_type), store_type
from transactions
group by store_type limit 1;

# 2. What is the count of male and female customers in the database?

select count(gender), gender
from customer
group by gender;

# 3. From which city do we have the maximum number of customers and how many?

select count(city_code), city_code
from customer
group by city_code 
order by count(city_code) desc limit 1;

# 4. How many sub categories are there under the books category?

select prod_cat, count(prod_cat)
from product_cat
group by prod_cat;

# 5. What is the maximum quantity of product ever orderd?

select max(qty)
from transactions;

# 6.What is the net total revenue generated in categories electronics and books?

select round(SUM(T.Total_amt),2) as Total_revenue 
from transactions as T 
inner join product_cat as P 
on  T.prod_cat_code=P.prod_cat_code and 
    T.prod_subcat_code = P.prod_sub_cat_code
where prod_cat in ('Electronics','Books');

# 7. How many customers have >10 transactions with us, excluding returns?

select count(cust_id) as TotalCustomers 
from(
    select cust_id,count(cust_id) as TotalCustomers 
from transactions  
group by cust_id 
having count(Transaction_id)>10) as T1;

# 8. What is the combined revenue earned from the 'electronics' and 'clothing' categories, from 'flagship stores'?

select round(sum(total_amt),2) as Total_Revenue 
from transactions as T
left join product_cat as P 
on T.prod_cat_code = P.prod_cat_code  and T.prod_subcat_code = P.prod_sub_cat_code
where T.Store_type like 'Flagship%' and P.prod_cat in ('Clothing ','Electronics');

# 9. What is the total revenue generated from 'male' customers in 'electronics' category? output should display total reveneu by subcat.

select P.prod_subcat, round(sum(T.total_amt),2) as Total_Revenue 
from transactions as T 
left join product_cat as P on T.prod_cat_code = P.prod_cat_code and T.prod_subcat_code = P.prod_sub_cat_code
left join customer as C on C.customer_Id = T.cust_id
where C.Gender='M' and P.prod_cat in('Electronics')
group by P.prod_subcat;

# 10. What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?

select Sub_Categories,round(sum(sales)/(
select sum(total_amt) 
  from transactions)*100,2) as Sales_in_Percentage,abs(round(sum(return)/(
select sum(total_amt) 
from transactions)*100,2) as Returns_in_Percentage
from (
    select P.prod_subcat as Sub_Categories, T.total_amt as Sales
    from transactions as T 
left join product_cat as P 
on T.prod_cat_code = P.prod_cat_code and T.prod_subcat_code = P.prod_sub_cat_code
where P.prod_subcat in (
    select P.prod_subcat  
    from transactions as T 
left join product_cat as P 
on T.prod_cat_code = P.prod_cat_code and T.prod_subcat_code = P.prod_sub_cat_code
group by  P.prod_subcat
order by sum(total_amt) desc limit 5)
) as T
group by Sub_Categories;

# 11. For all customers aged between 25 to 35 years find what is the net total reveneu generated by these consumers in last 30 days of transactions from max transactiondate available in the data?

select round(sum(total_amt),2) as Total_Revenue  
from transactions as T 
inner join customer as C on T.cust_id = C.customer_Id
where DATE_DIFF(Year, convert(date,DOB,105),(select MAX(convert(date,tran_date,105)) as d 
from transactions )) 
between 25 and 35 
and DATE_DIFF(day,(select MAX(convert(date,tran_date,105)) as d 
from transactions  ),
dateadd(day,-30,(select MAX(convert(date,tran_date,105)) as d 
from transactions)))=-30 ;

# 12. Which product category has seen the max value of returns in last 3 months of transaction?
 
select P.Prod_cat from product_cat as P 
left join transactions as T 
on T.prod_cat_code = P.prod_cat_code and T.prod_subcat_code = P.prod_sub_cat_code
where total_amt and DATEDIFF(month,(select MAX(convert(date,tran_date,105)) as d 
from transactions  ),
dateadd(month,-3,(select MAX(convert(date,tran_date,105)) as d from transactions))=-3 
group by P.Prod_cat
order by count(transaction_id) desc limit 1;

# 13.Which store-type sells the maximum products; by value of sales amount and by quantity sold?

select  Store_type 
from(select Store_type ,sum(total_amt) as total_sales, sum(Qty) as total_Quantity 
from transactions 
group by Store_type 
order by total_sales desc,total_Quantity desc limit 1) as T1;

# 14. What are the categories for which average revenue is above the overall average.

select Prod_cat as Categories 
from (select P.Prod_cat,AVG(total_amt) as Avrage 
from product_cat as P
inner join transactions as T 
on T.prod_cat_code = P.prod_cat_code and T.prod_subcat_code = P.prod_sub_cat_code 
group by P.prod_cat
having AVG(total_amt) > (
    select AVG(total_amt) 
    from transactions)) as T2

# 15.Find the average and total revenue by each sub category for the categories which are among top 5 categories in terms of quantity sold.

with TBL1 as (select  prod_cat_code,sum(qty) as tot_qty from transactions group by prod_cat_code
order by tot_qty desc limit 5),
TBL2 as ( select P.Prod_subcat,P.prod_cat,T.prod_cat_code,round(AVG(T.total_amt),2) as Average,
round(SUM(T.total_amt),2) as Total_Revenue 
from product_cat as P
inner join transactions as T 
on T.prod_cat_code = P.prod_cat_code and T.prod_subcat_code = P.prod_sub_cat_code 
group by T.prod_cat_code,P.prod_subcat,P.prod_cat)
select TBL2.* from TBL1 inner join TBL2 on TBL2.prod_cat_code = TBL1.prod_cat_code;
